### ISSUE TITLE
Pilot US dataset: data.gov

### ISSUE THREAD

**Issue by sumikasan** [theodi/open-data-certificate#1089]
To test if auto-certification work for data.gov, including the metadata quality, what % of their datasets will get raw.

Test using the staging site.

**Comment by pkqk** [comment]
I've not run a full import on staging yet due to some reliability issues in the import code[1]

It probably will also require making the licensing questions in the US jurisdiction a bit more strict, currently if no answer is provided for the initial licensing question of if the data was created by the US govt or not then most certificates will pass. We need a way to work out if each dataset is federal data[2] or some other body.

If we can work out what data is Federal then they will mostly likely pass depending on how we deal with the Public Domain within the US issue.

[1]: As the data.gov dataset is so large the chance of a request failing due to intermittent issues is higher, currently there's very little retry logic.
[2]: Federal data is explicitly PD inside the US but outside requires a licence, data by other bodies may be anything.

**Comment by pkqk** [comment]
1. Reliability has been split out to #1140
  2. Licensing questions to #1138
  3. And determining the producer to #1139
