### ISSUE TITLE
Editing unpublished questionnaire creates a new copy

### ISSUE THREAD

**Issue by pkqk** [theodi/open-data-certificate#1111]
Re-editing a questionnaire that is not yet published (but maybe has been marked as completed as it attained raw level) creates a new copy each time.

I think the flow should be
  - if certificate is unpublished then edit the questionnaire
  - if published then a new unpublished copy should be created to work on.
    - may need extra checks to stop creating multiple drafts.

**Comment by SeivadLR** [comment]
This is LRs Issue,  The copied data is incomplete.  If I can't edit my existing certfificate in Place then Please copy it entirely. @dataadmingroup

**Comment by pkqk** [comment]
Hi @SeivadLR, could you send me a link to a certificate that's causing this problem for you?

**Comment by LR-Technology-Group** [comment]
I am also getting service unavailable when I try to edit my certificate and have been since Wednesday.
here is the link from the dashboard edit questionnaire button
https://certificates.theodi.org/surveys/gb/WAlKYCmkFA/continue

this is the same certs view button link
https://certificates.theodi.org/datasets/625/certificates/48157
and here is the certificate view link created by the failed/failing edits 
https://certificates.theodi.org/datasets/619/certificates/48495

In the course of doing this my dashboard now had 4 entries for this certificate and I am getting link not found when I click oK to delete the one's I don't want.
![odi cert fir 15-5 issue](https://cloud.githubusercontent.com/assets/5636851/7652727/4d22a386-fb07-11e4-8a94-b86e83b9bb19.PNG)

![odi cert sec 15-5 issue](https://cloud.githubusercontent.com/assets/5636851/7652743/7a8c30ee-fb07-11e4-8c8d-5ba7b5f55bd3.PNG)
When I selected other than the first certificate in the list on the dashboard.  the top one deleted OK. but took out the second one.  could have been a browser refresh issue....

**Comment by LR-Technology-Group** [comment]
Updated comments on GitHUB.
Land Registry is the definitive source of information for more than 24 million property titles in England and Wales. Since 1862 we have provided security and confidence in one of the most active property and mortgage markets in the world. We are working to support economic growth and data transparency as part of the Public Data Group. Find out more at www.gov.uk/land-registry

If you have received this e-mail and it was not intended for you, please let us know, and then delete it. Please treat our communications in confidence, as you would expect us to treat yours. Land Registry checks all mail and attachments for known viruses, however, you are advised that you open any attachments at your own risk.

The original of this email was scanned for viruses by the Government Secure Intranet virus scanning service supplied by Vodafone in partnership with Symantec. (CCTM Certificate Number 2009/09/0052.) This email has been certified virus free.
Communications via the GSi may be automatically logged, monitored and/or recorded for legal purposes.

**Comment by sumikasan** [comment]
@SeivadLR, we are trying to fix as a matter of urgency - I fully appreciate that this is very frustrating for everyone. Please could you wait until the fix is deployed so prevent any further loss of data / info. 

Many apologies for causing inconvenience and thank you in advance for your patience.

**Comment by pkqk** [comment]
Managed to narrow down the issue.

There are several cases in which a questionnaire can't just be edited but needs a new copy to be created.

These are:
  1. If the certificate has been published
  2. If the jurisdiction for the certificate is being changed
  3. or in this case the `Survey` has been updated and the responses need to be matched up to the newer version of the questionnaire.

This part of the code is so slow Chrome appears to be attempting to make multiple requests as it thinks there is internet connectivity issues. This is causing the code to try and make several copies and causing deadlocks in the database.

This is due to the fact that the `Edit Questionnaire` button is performing a `GET` request which web browsers are allowed to request more than once. I'm going to first put out a fix that changes this to be done by a `POST` request which browsers are only allowed to do once as it means that request makes changes that can't be done more than once.

The copying code will still be slow so the page may still time out (it seems to take about 2 minutes to copy) but after going back to the dashboard you'll be able to press `Edit Questionnaire` a second time and it should be able to load the new copy.

Once that is out then I'll start optimising the copy code and this should become much more usable.

**Comment by pkqk** [comment]
I'll deploy the changes that prevent the copy being run more than once.

The issue of speed has been moved to #1142
