### ISSUE TITLE
Level attained "checklist" for Open Data Certs

### ISSUE THREAD

**Issue by mattwagstaff** [theodi/open-data-certificate#1173]
Hi all, I'm currently undertaking a discovery piece to try and understand what is required at what level of Certificate in a more structured way. The current explanation of the Certificate is mainly words on the ODI website (https://certificates.theodi.org/overview), but I'm wondering if a "checklist' of sorts already exists for this? I've attached an excerpt of what I've been working on - I'd love to know if someone has refined this more, or if it's already provided by the ODI.

Thanks in advance.

![capture](https://cloud.githubusercontent.com/assets/7855745/8221310/37451e46-15a0-11e5-9121-2ee387da4465.PNG)

**Comment by Stephen-Gates** [comment]
+1

**Comment by sumikasan** [comment]
I have attempted to do this myself as it has been requested by many of our users. Difficulty is that a lot of questions asked to achieve a certain level may or may not be needed if you answer some questions in a certain way. The way it has been designed is highly dynamic so this makes it very hard to map in tabular format.

Saying that, we do have a very high level version in a tabulated format that our training team has produced - will that helpful?

@Stephen-Gates - we love your flowchart you did to make it human readable: we are going to replicate it so we can map whole questionnaire and will be available for everyone. That is now on the roadmap, to be delivered in the next two months so watch this space!

**Comment by Stephen-Gates** [comment]
@iamwagz are you trying to understand what metadata attributes are required to earn each level of certificate? I get that impression from the Explicit Element column. I think this is important to understand so the questionnaire answers can be pre-filled or certificates automatically awarded.  

Here's my attempt at flowcharting the legal part of the certificate questionnaire @sumikasan referred to. No guarantees it reflects the latest questions or is correct but for what it's worth... 
- [Licence flowchart](https://stephen-gates.github.io/certificates/ODCLegalLicence.pdf)
- [Privacy flowchart](https://stephen-gates.github.io/certificates/ODCLegalPrivacy.pdf)
- [Rights flowchart](https://stephen-gates.github.io/certificates/ODCLegalRights.pdf)

**Comment by iamwagz** [comment]
@Stephen-Gates yes, that's exactly what I'm aiming for with this. Those flows are very useful, though like you said, for more explicit automation in future and to understand *why* a certain type is awarded instead of another (eg: if you fail just one element of what's required for "pilot", you instead get awarded "raw"). I'm hoping to visualise this in a way that's easier to read eventually though, as the ODI link that I posted also references process and policy elements of a business as well. These components aren't really able to be captured as "metadata" as such as it's more a 'state of the business' adopting it.

@sumikasan thanks for the reply. It's definitely dynamic but I think as the requirements change, the check list to obtain certain levels of certificate should change as well. Is this safe to assume? If so, I would love to see the ODI adopt this line of thinking and keep this kind of list updated to enable businesses to streamline process (automate) releasing datasets with an ODI certificate attached (this is where @Stephen-Gates thoughts are going I believe). Anything you've got to show me would be helpful to grasp how your teams are capturing it. On that point, I'm wondering if the tool you have online to give datasets certificates has some sort of logic built into it to award these... is this logic available to see?

**Comment by mattwagstaff** [comment]
@sumikasan I'm assuming, since you added this to the milestone event, we should see something like this from ODI at the end of July?

**Comment by sumikasan** [comment]
@mattwagstaff - sorry for late response (I was away); it's high on the list of things to do, but we are still reviewing our backlog so I can't confirm yet but will let you know next week when we will be running a sprint planning session.

**Comment by mattwagstaff** [comment]
@sumikasan No problem mate - I know you guys are busy. Thanks for the update - keep me in the loop next week. It's a little messy but I've near on completed what I think is a pretty comprehensive checklist for the certificates in a spreadsheet. If I can provide helpful input anywhere in your process, I'd love to assist.

**Comment by sumikasan** [comment]
@mattwagstaff - marvellous! I will definitely take up on your offer so thank you! :-)

**Comment by pezholio** [comment]
This is what we have so far:

http://staging.certificates.theodi.org/flowchart

The only remaining issue (I think) is that we are missing an entire chunk of questions from the legal section:

https://github.com/theodi/open-data-certificate/blob/staging/prototype/jurisdictions/certificate.GB.xml#L70-L119

This is caused because there are multiple dependencies, meaning we'll probably need to duplicate questions somewhere along the line. I'm currently working on moving from using the XML to drive the flowcharts to using the application database. 

@mattwagstaff If you have any ideas, that would be great :+1:

**Comment by Stephen-Gates** [comment]
Thanks for progressing this. Are you planning to: 
- also identify "Raw" certificate requirements? 
- follow up on @mattwagstaff's work and identify which metadata elements can answer a question?

I'm presenting to a government in november on certificates. I would love to be able to: 
- state the metadata that is needed to earn a raw or pilot certificate automatically (and how that can be complemented with default setting in the automatic awarding of certificates)
- show the minimum questions that need to be answered to earn a raw/pilot certificate.

Your work is helping me towards this - thank you.

**Comment by mattwagstaff** [comment]
@pezholio The flow chart is looking great mate - side note - are you building that as a dynamic SVG with Mermaid Chart (https://github.com/knsv/mermaid)? Really impressive!

Just a few points, I think it might be a little confusing as to what certain parts are achieving. It needs the questions aligned (....this will probably be difficult) somehow to reach a level of certificate as the user follows the chart further. Telling a story as such: "reach step 5 and receive a Raw cert, step 15 is a Standard cert" etc.. So the deeper you scroll right/down, the more on the path you are to achieving Exemplar. There are some questions where the answers all go to the same next step and Pilot level colours appearing further down the flow than Exemplar ones. 

I'm picturing:
Take regular backups? 
Yes > Next step in flow on way to Standard
No > Pilot Cert achieved. (or Raw depending on other answers up to that point)

I actually have a speadsheet with the certificate requirements (off the ODI certificate page  https://certificates.theodi.org/overview) for each level already together, it's a little wordy but fairly straight forward. Would this help?

I'm trying to turn this into a webpage with some clear cut requirements for each level. So, similar to what you're doing but without the flow, simply listing the Main, Legal, Practical, Social and Technological requirements in Metadata, Business Process, Web Tech and Documents for each level of certificate.

I'm about 30% of the way through this. Trying to semi-match the style and coding with CSS and Bootstrap so the ODI can implement with their site fairly easily should they want to. In essence, I'm trying to turn this: https://certificates.theodi.org/overview into a less verbose and more "tick a box" style of page. This is essentially what I've done with my spreadsheet, but now I'm trying to fine tune it even more....and make it a lot prettier! :)

**Comment by pezholio** [comment]
@mattwagstaff Thanks for the feedback - I think we've hit the limits of what we can achieve with autogeneration - and there's still a lot missing from the flowcharts I've built already, so we're thinking of farming this out to a specialist datavis expert / designer. It would be great if you could share the spreadsheet you have already - would save me having to do the work all over again :smile:

**Comment by mattwagstaff** [comment]
@pezholio No problem. Interested to keep following this and see it progress. Again, I have experience in this area, so if you need input or assistance I'm more than happy. 

If you throw me your email address, I'll send the spreadsheet to you. It's not perfect and a little messy, but it attempts to make it more clear cut. I've also started my own project, as I mentioned above, to turn this into a webpage of sorts. I have uploaded it to Github here: 

https://github.com/mattwagstaff/ODICert_turnKey

**Comment by mattwagstaff** [comment]
File uploaded [here](https://www.dropbox.com/s/iyslk1pxuwji05d/odiCerts.xlsx?dl=0).

**Comment by shevski** [comment]
I created a table to add to the badge level about page - see https://github.com/theodi/shared/issues/856
which acts as a very simple checklist overview

**Comment by Stephen-Gates** [comment]
suggest this can be closed because:

- complexity in documenting requirements due to question dependencies 
- https://certificates.theodi.org/en/about/badgelevels

**Comment by rachelwilson** [comment]
Closing, but a very useful issue for documentation purposes! Thanks everyone who contributed.
