### ISSUE TITLE
Set up a workflow for translating the certificates app

### ISSUE THREAD

**Issue by dicknorris** [theodi/open-data-certificate#1251]
Some components of the certificates app cannot currently be translated, including error messages and check boxes.

We need to have a workflow in place that allows these to be translated by localisation teams.  This approach should be consistent with the rest of the localisation workflow, and should incorporate Transifex.

 - [ ] Make sure all sections of website are localizable:
   - [ ] Website interface (menubar, links etc)
   - [x] Questionnaire start page
   - [ ] Questionnaire interface (interface, error and validation messages)
   - [ ] Questionnaire progress section
   - [ ] How to improve section
 - [ ] Make push/pull of translations to Transifex, scripted and automatable.

**Comment by zoul** [comment]
Related issues: #1236 (Improve code support for pluralization) and #1240 (Provide more context for localization).

**Comment by tonymarklove** [comment]
Closing. This was covered by #1270

**Comment by zoul** [comment]
So what does the Transifex workflow look like now? If I update a translation in Transifex, will the change appear automatically in the ODC web app?

**Comment by michalkuban** [comment]
:+1:

**Comment by tonymarklove** [comment]
There is still a manual process of pulling down changes from Transifex into the web app. Due to the way we want the code for this to work, I think that will always be the case. If it starts to become a bottleneck we can look into making it more automatic.

Yes, any new English strings should show up in Transifex as untranslated. I guess we might need something set up to alert translators when new English strings have been added.
