### ISSUE TITLE
Questionnaire mixes questions from two languages

### ISSUE THREAD

**Issue by zoul** [theodi/open-data-certificate#1295]
Even though I have both the jurisdiction and the language set to Czech, the questionnaire mixes English and Czech questions in the Law section:

![screenshot of the problem](https://cloud.githubusercontent.com/assets/95329/10361507/d8f65f10-6da8-11e5-88d8-71a5f0d9d8d2.png)

**Comment by tonymarklove** [comment]
I've just had a look at this. There is no real bug here, just needs the surveys to be rebuilt with the latest translations. I've been working on streamlining this whole process because it's not as smooth as it could be.

I'm happy to leave this issue open as a reminder until I get everything updated on staging.

**Comment by zoul** [comment]
Great, thanks. Is there a way to know which revision is currently deployed to the staging and production environments?

**Comment by tonymarklove** [comment]
This should all be up-to-date on staging now. So I'll close the issue. Feel free to re-open if that's not the case.
