### ISSUE TITLE
Issues with viewing the main page of certificate in Internet Explorer 11

### ISSUE THREAD

**Issue by michalkuban** [theodi/open-data-certificate#1365]
There are some bugs when using Interner Explorer v.11 for Open Data Certificate. The second bottom part of the screen is not screening correctly. 
![od certificate - mx](https://cloud.githubusercontent.com/assets/8858125/11393553/8f93fbec-9360-11e5-9fea-35fc0d249b85.GIF)

**Comment by mormegil-cz** [comment]
Not only that, the site is ±completely broken in IE11 for me. _Invalid character_ in application.js (in the HTML encoder or whatisthat using an I-believe-valid-but-a-bit-strange `ˇ:"caron"` syntax, which IE seems not to accept, erroneously, [it seems](http://unicode.org/cldr/utility/character.jsp?a=02C7).). E.g. the _Create a certificate_ link leads to https://certificates.theodi.org/en/surveys#start-cert-modal instead of displaying the modal dialog.

**Comment by shevski** [comment]
@michalkuban how is it now with the new homepage? Please create a new issue if it's still a problem!
