### ISSUE TITLE
Run against some portals on staging

### ISSUE THREAD

**Issue by Floppy** [theodi/open-data-certificate#1418]
Add some portals here to test against.

**Comment by Stephen-Gates** [comment]
If you're looking for CKAN portals to test, here's my top 3:
- https://data.qld.gov.au 
- http://data.sa.gov.au
- https://data.brisbane.qld.gov.au

Or [my full list](http://queensland.theodi.org/home/resources/data/). Note: they're not all CKAN portals.

**Comment by Floppy** [comment]
Canada: http://open.canada.ca

**Comment by Stephen-Gates** [comment]
To test an organisation within a portal try http://data.sa.gov.au/data/organization/department-of-planning-transport-and-infrastructure

**Comment by digitalWestie** [comment]
- https://data.qld.gov.au works
- http://data.sa.gov.au mostly works but broke with datasets that were links to other portals
- https://data.brisbane.qld.gov.au/ works (tested with 'recreation' subset)
- http://open.canada.ca/data/en/api works (but had a lot of unanswered questions)

**Comment by Stephen-Gates** [comment]
Thanks @digitalWestie for testing the Australian portals.

I assume this was tested locally as I don't see the results on http://staging.certificates.theodi.org/en/datasets (which by the way isn't rendering fully for me).

What will be the approach for portal owners that harvest from other portals and encounter the data.sa.gov.au issue above? Should they run a collection of organisation based campaigns or just ignore the errors from a full run?

**Comment by Floppy** [comment]
The data.sa.gov.au issue is in #1436, and is on the list to resolve - hopefully we can make it follow the proper links.

**Comment by digitalWestie** [comment]
See #1442 

But just as I pushed this up I realised, do we really want to include harvested datasets in these campaigns? Do we not want to run campaigns against a specific portal? Not just any that it comes across?

**Comment by Stephen-Gates** [comment]
@digitalWestie No you don't want to include them.  Just elegantly ignore them (that's what I meant in my last comment above). 

To scan my whole portal and not get any errors due to harvested metadata, I would prefer that I just specify the portal (e.g. data.sa.gov.au) and the campaign intelligently ignores harvested metadata.

I'm not sure how you are determining what is harvested from elsewhere. My guess was by organisation, hence my question "Should they run a collection of organisation based campaigns [to avoid getting errors when running the campaign]?".

Hope that's clear - sorry.

**Comment by Stephen-Gates** [comment]
Can this be closed given  #1442 ?
